import React, { useEffect, useRef, useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { Code, ZoomIn, ZoomOut, Copy, Check, RefreshCw, Maximize2, Minimize2 } from 'lucide-react';
import mermaid from 'mermaid';

// Initialize mermaid configurations safely
try {
  mermaid.initialize({
    startOnLoad: false,
    theme: 'dark',
    securityLevel: 'loose',
    themeVariables: {
      background: 'transparent',
      primaryColor: '#1e1b4b', // Deep indigo
      primaryTextColor: '#f8fafc',
      primaryBorderColor: '#312e81',
      lineColor: '#64748b',
      secondaryColor: '#0f172a',
      tertiaryColor: '#1e293b'
    },
    flowchart: {
      useMaxWidth: true,
      htmlLabels: true,
      curve: 'basis'
    },
    themeCSS: `
      .node rect, .node circle, .node polygon, .node path {
        fill: #0a0a14 !important;
        stroke: #f97316 !important;
        stroke-width: 1.5px !important;
      }
      .edgePath .path {
        stroke: #64748b !important;
        stroke-width: 1.5px !important;
      }
      .label {
        font-family: 'Inter', system-ui, sans-serif !important;
        color: #e2e8f0 !important;
      }
      .edgeLabel rect {
        fill: #09090b !important;
        opacity: 0.8;
      }
      .labelText, .edgeLabel {
        fill: #94a3b8 !important;
        font-size: 11px !important;
        font-weight: 600 !important;
      }
    `
  });
} catch (e) {
  console.error("Failed to initialize mermaid: ", e);
}

interface MermaidRendererProps {
  chartCode: string;
}

export const MermaidRenderer: React.FC<MermaidRendererProps> = ({ chartCode }) => {
  const containerId = useRef(`mermaid-canvas-${Math.random().toString(36).substring(2, 9)}`);
  const [svgContent, setSvgContent] = useState<string>('');
  const [errorOnRender, setErrorOnRender] = useState<string | null>(null);
  const [isRendering, setIsRendering] = useState(true);
  const [copied, setCopied] = useState(false);
  const [zoomScale, setZoomScale] = useState(1);
  const [isFullscreen, setIsFullscreen] = useState(false);

  useEffect(() => {
    let active = true;
    const renderChart = async () => {
      if (!chartCode) return;
      setIsRendering(true);
      setErrorOnRender(null);

      try {
        // Clear previous cache or element references
        const cleanChartCode = chartCode.trim();
        const { svg } = await mermaid.render(containerId.current, cleanChartCode);
        if (active) {
          setSvgContent(svg);
          setIsRendering(false);
        }
      } catch (err: any) {
        console.error("Mermaid parsing failure: ", err);
        // Clear bad internal states or elements generated by failed rendering
        const badElement = document.getElementById(containerId.current);
        if (badElement) badElement.remove();

        if (active) {
          setErrorOnRender(err?.message || "Invalid Mermaid Diagram Syntax.");
          setIsRendering(false);
        }
      }
    };

    renderChart();

    return () => {
      active = false;
    };
  }, [chartCode]);

  const handleCopySource = async () => {
    try {
      await navigator.clipboard.writeText(chartCode);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error(err);
    }
  };

  const handleZoomIn = () => setZoomScale(prev => Math.min(prev + 0.15, 2.0));
  const handleZoomOut = () => setZoomScale(prev => Math.max(prev - 0.15, 0.5));
  const handleResetZoom = () => setZoomScale(1);

  return (
    <div className={`relative border border-border-main rounded-2xl bg-bg-surface overflow-hidden my-4 shadow-lg ${isFullscreen ? 'fixed inset-4 z-50 flex flex-col' : 'w-full'}`} id="mermaid-renderer-outer">
      {/* Chrome Top Header bar */}
      <div className="flex items-center justify-between border-b border-border-subtle bg-bg-base/60 px-4 py-2.5">
        <div className="flex items-center space-x-2">
          <Code size={14} className="text-accent-saffron" />
          <span className="text-xs font-black tracking-wider uppercase text-text-secondary">Welfare Workflow Engine</span>
        </div>
        
        {/* Actions panel */}
        <div className="flex items-center space-x-1.5">
          <button
            onClick={handleCopySource}
            className="p-1.5 bg-bg-surface hover:bg-bg-elevated border border-border-subtle text-text-secondary hover:text-text-primary rounded-lg transition-colors cursor-pointer"
            title="Copy Diagram Source Code"
          >
            {copied ? <Check size={14} className="text-success" /> : <Copy size={14} />}
          </button>
          
          <button
            onClick={handleZoomOut}
            disabled={isRendering || !!errorOnRender}
            className="p-1.5 bg-bg-surface hover:bg-bg-elevated border border-border-subtle text-text-secondary hover:text-text-primary rounded-lg transition-colors cursor-pointer disabled:opacity-55"
            title="Zoom Out"
          >
            <ZoomOut size={14} />
          </button>

          <button
            onClick={handleResetZoom}
            disabled={isRendering || !!errorOnRender}
            className="px-2 py-1 bg-bg-surface hover:bg-bg-elevated border border-border-subtle text-[11px] leading-tight font-bold text-text-secondary hover:text-text-primary rounded-lg transition-colors cursor-pointer disabled:opacity-55"
            title="Reset Zoom"
          >
            {Math.round(zoomScale * 100)}%
          </button>

          <button
            onClick={handleZoomIn}
            disabled={isRendering || !!errorOnRender}
            className="p-1.5 bg-bg-surface hover:bg-bg-elevated border border-border-subtle text-text-secondary hover:text-text-primary rounded-lg transition-colors cursor-pointer disabled:opacity-55"
            title="Zoom In"
          >
            <ZoomIn size={14} />
          </button>

          <button
            onClick={() => setIsFullscreen(!isFullscreen)}
            disabled={isRendering || !!errorOnRender}
            className="p-1.5 bg-bg-surface hover:bg-bg-elevated border border-border-subtle text-text-secondary hover:text-text-primary rounded-lg transition-colors cursor-pointer disabled:opacity-55"
            title={isFullscreen ? "Exit Fullscreen" : "Fullscreen Preview"}
          >
            {isFullscreen ? <Minimize2 size={14} /> : <Maximize2 size={14} />}
          </button>
        </div>
      </div>

      {/* Rendering State, error handling or diagram container viewport */}
      <div className={`relative flex-1 p-6 flex justify-center items-center overflow-auto min-h-[280px] bg-bg-base/40`}>
        <AnimatePresence mode="wait">
          {isRendering && (
            <motion.div
              key="loading"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="flex flex-col items-center space-y-2 text-text-muted"
            >
              <RefreshCw size={24} className="animate-spin text-accent-saffron" />
              <span className="text-xs font-bold animate-pulse">Designing workflow flowchart...</span>
            </motion.div>
          )}

          {!isRendering && errorOnRender && (
            <motion.div
              key="error"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="p-4 bg-error/10 border border-error/20 rounded-xl max-w-sm text-center"
            >
              <p className="text-xs font-bold text-error">Mermaid Engine Exception</p>
              <p className="text-[11px] text-text-secondary mt-1 max-h-24 overflow-y-auto font-mono text-left bg-black/30 p-2 rounded border border-border-subtle">
                {errorOnRender}
              </p>
            </motion.div>
          )}

          {!isRendering && !errorOnRender && svgContent && (
            <motion.div
              key="svg-diagram"
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ duration: 0.3 }}
              style={{ transform: `scale(${zoomScale})`, transformOrigin: 'center center' }}
              className="transition-transform duration-100 ease-out flex items-center justify-center max-w-full"
              dangerouslySetInnerHTML={{ __html: svgContent }}
            />
          )}
        </AnimatePresence>
      </div>
    </div>
  );
};
